/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as DestinationRouteImport } from './routes/destination'
import { Route as CrewRouteImport } from './routes/crew'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PagesHomepaageRouteImport } from './routes/pages/homepaage'
import { Route as PagesCrewIndexRouteImport } from './routes/pages/crew/index'

const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationRoute = DestinationRouteImport.update({
  id: '/destination',
  path: '/destination',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewRoute = CrewRouteImport.update({
  id: '/crew',
  path: '/crew',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesHomepaageRoute = PagesHomepaageRouteImport.update({
  id: '/pages/homepaage',
  path: '/pages/homepaage',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesCrewIndexRoute = PagesCrewIndexRouteImport.update({
  id: '/pages/crew/',
  path: '/pages/crew/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crew': typeof CrewRoute
  '/destination': typeof DestinationRoute
  '/technology': typeof TechnologyRoute
  '/pages/homepaage': typeof PagesHomepaageRoute
  '/pages/crew': typeof PagesCrewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crew': typeof CrewRoute
  '/destination': typeof DestinationRoute
  '/technology': typeof TechnologyRoute
  '/pages/homepaage': typeof PagesHomepaageRoute
  '/pages/crew': typeof PagesCrewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crew': typeof CrewRoute
  '/destination': typeof DestinationRoute
  '/technology': typeof TechnologyRoute
  '/pages/homepaage': typeof PagesHomepaageRoute
  '/pages/crew/': typeof PagesCrewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crew'
    | '/destination'
    | '/technology'
    | '/pages/homepaage'
    | '/pages/crew'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crew'
    | '/destination'
    | '/technology'
    | '/pages/homepaage'
    | '/pages/crew'
  id:
    | '__root__'
    | '/'
    | '/crew'
    | '/destination'
    | '/technology'
    | '/pages/homepaage'
    | '/pages/crew/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrewRoute: typeof CrewRoute
  DestinationRoute: typeof DestinationRoute
  TechnologyRoute: typeof TechnologyRoute
  PagesHomepaageRoute: typeof PagesHomepaageRoute
  PagesCrewIndexRoute: typeof PagesCrewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destination': {
      id: '/destination'
      path: '/destination'
      fullPath: '/destination'
      preLoaderRoute: typeof DestinationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crew': {
      id: '/crew'
      path: '/crew'
      fullPath: '/crew'
      preLoaderRoute: typeof CrewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/homepaage': {
      id: '/pages/homepaage'
      path: '/pages/homepaage'
      fullPath: '/pages/homepaage'
      preLoaderRoute: typeof PagesHomepaageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/crew/': {
      id: '/pages/crew/'
      path: '/pages/crew'
      fullPath: '/pages/crew'
      preLoaderRoute: typeof PagesCrewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrewRoute: CrewRoute,
  DestinationRoute: DestinationRoute,
  TechnologyRoute: TechnologyRoute,
  PagesHomepaageRoute: PagesHomepaageRoute,
  PagesCrewIndexRoute: PagesCrewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
